### ISSUE TITLE
[Feature Suggestion] Run Provider Commands as Another User

### ISSUE THREAD

**Issue by DWSR** [flynnhandley/hashicorp-plugins#1]
I'd love the ability to support running the PowerShell commands as different user from Terraform. Reasons why this might be useful:

- Separation of roles. I can execute Terraform as an unprivileged user, then run only the commands that I need to as a privileged user. This helps in scenarios where administrative users are not able to login to workstation.
- Inter-forest administration with no or one-way trusts: If my current user is not valid on the remote machine, and/or that user is not valid on my machine, I need the ability to change users.

**Comment by flynnhandley** [comment]
Hi, @DWSR, thanks for the feedback.
How would you suggest we handle authentication? What is the difference between what you have requested and using runas? (other than the Terraform process runs as a non-elevated user).

How do you currently go about running PowerShell commands as a different user in your environment?
