### ISSUE TITLE
Can't Build Because of Missing Dependency 

### ISSUE THREAD

**Issue by synax** [flynnhandley/hashicorp-plugins#3]
I tried to build the project and was not able to vendor the dependency ["common/psremote/hvremote"](https://github.com/flynnhandley/hashicorp-plugins/blob/f59892bab33f590fbec8979b49e4a20550dcc521/hyperv/driver_ps_5.go#L11). Where can I get this package from?

**Comment by mo-man** [comment]
Hi Synax, have you tried here? https://github.com/hashicorp/packer/tree/master/common/powershell

**Comment by synax** [comment]
Hi Mo-Man, yes I had a look at this as well. But this is the PowerShell based HyperV package from packer, which uses local PowerShell commands to interact with HyperV. I guess the hvremote uses PowerShell remoting to connect to a remote hyperv host. For example the "NewHypervRemote" function does not exist in the hyperv package from packer. `var hv, _ = hvremote.NewHypervRemote(userName, password, computerName, useSSL)`. I had a chat with @taliesins, and he is also working on a provider for HyperV (I'ts still alpha). I've also started to experiment with it my self, and I think his approach is very promising. [terraform-provider-hyperv](https://github.com/taliesins/terraform-provider-hyperv)

**Comment by flynnhandley** [comment]
This has been fixed, thanks @uberjew666
